
export const THEMES = [
  {
    id: "savanna",
    name: "Sunrise Savanna",
    gradient: "linear-gradient(-45deg, #FF512F, #DD2476, #FF9966, #FF5E62)",
    textColor: "#FFFFFF",
    accentColor: "#FFD700",
    icon: "🌅",
    animationType: "drop",
  },
  {
    id: "river",
    name: "River Crossing",
    gradient: "linear-gradient(-45deg, #2193b0, #6dd5ed, #2980b9, #6dd5ed)",
    textColor: "#FFFFFF",
    accentColor: "#E0F7FA",
    icon: "🌊",
    animationType: "slide",
  },
  {
    id: "jungle",
    name: "Jungle Trek",
    gradient: "linear-gradient(-45deg, #11998e, #38ef7d, #0575E6, #021B79)",
    textColor: "#FFFFFF",
    accentColor: "#76FF03",
    icon: "🌴",
    animationType: "pop",
  },
  {
    id: "village",
    name: "Village Build",
    gradient: "linear-gradient(-45deg, #FFB75E, #ED8F03, #d299c2, #fef9d7)",
    textColor: "#5D4037",
    accentColor: "#8D6E63",
    icon: "🏘️",
    animationType: "spin",
  },
  {
    id: "celebration",
    name: "Celebration Night",
    gradient: "linear-gradient(-45deg, #12c2e9, #c471ed, #f64f59, #667eea)",
    textColor: "#FFD700",
    accentColor: "#E1BEE7",
    icon: "✨",
    animationType: "zoom",
  },
];
